In [1]:
import os
import pandas as pd
import numpy as np
import re

In [28]:
#loading in the dataset 
df = pd.read_excel('Table1 2004.xls')

In [29]:
#renaming the column names 
df = df.rename(columns={"Table 1": "Bias motivation", "Unnamed: 1": "Incidents", "Unnamed: 2": "Offenses", 
                  "Unnamed: 3": "Victims", "Unnamed: 4": "Known Offenders"})

In [30]:
#removing unneeded rows and resetting the index 
df = df.loc[5:30, :].set_index('Bias motivation')

In [31]:
df = df.rename(index=lambda s: re.sub(r'\d+$', '', s)) #removing any digits inside the index column 
df

,Incidents,Offenses,Victims,Known Offenders
Bias motivation,,,,
Anti-White,829,998,1027,1085
Anti-Black,2731,3281,3475,2694
Anti-American Indian/Alaskan Native,83,97,100,97
Anti-Asian/Pacific Islander,217,252,266,188
"Anti-Multiple Races, Group",182,235,251,109
Religion:,1374,1480,1586,604
Anti-Jewish,954,1003,1076,330
Anti-Catholic,57,57,68,37
Anti-Protestant,38,43,48,28
Anti-Islamic,156,193,201,124
Anti-Other Religion,128,140,147,68
"Anti-Multiple Religions, Group",35,37,39,14
Anti-Atheism/Agnosticism/etc.,6,7,7,3
Sexual Orientation:,1197,1406,1482,1258
Anti-Male Homosexual,738,855,902,832
Anti-Female Homosexual,164,201,212,163
Anti-Homosexual,245,297,314,224
Anti-Heterosexual,33,35,36,22
Anti-Bisexual,17,18,18,17
Ethnicity/National Origin:,972,1201,1254,1047
Anti-Hispanic,475,611,646,585
Anti-Other Ethnicity/National Origin,497,590,608,462
Disability:,57,71,73,54
Anti-Physical,23,23,24,16
Anti-Mental,34,48,49,38
Multiple-Bias Incidents,7,14,14,9

In [33]:
#dropping rows that are not needed (the totals)
df = df.drop(df.index[5])
df = df.drop(df.index[12])
df = df.drop(df.index[-4])
df = df.drop(df.index[-6])

df

,Incidents,Offenses,Victims,Known Offenders
Bias motivation,,,,
Anti-White,829,998,1027,1085
Anti-Black,2731,3281,3475,2694
Anti-American Indian/Alaskan Native,83,97,100,97
Anti-Asian/Pacific Islander,217,252,266,188
"Anti-Multiple Races, Group",182,235,251,109
Anti-Jewish,954,1003,1076,330
Anti-Catholic,57,57,68,37
Anti-Protestant,38,43,48,28
Anti-Islamic,156,193,201,124
Anti-Other Religion,128,140,147,68
"Anti-Multiple Religions, Group",35,37,39,14
Anti-Atheism/Agnosticism/etc.,6,7,7,3
Anti-Male Homosexual,738,855,902,832
Anti-Female Homosexual,164,201,212,163
Anti-Homosexual,245,297,314,224
Anti-Heterosexual,33,35,36,22
Anti-Bisexual,17,18,18,17
Anti-Hispanic,475,611,646,585
Anti-Other Ethnicity/National Origin,497,590,608,462
Anti-Physical,23,23,24,16
Anti-Mental,34,48,49,38
Multiple-Bias Incidents,7,14,14,9

In [34]:
race = df[:5]
race

                                    Incidents Offenses Victims Known Offenders
Bias motivation
Anti-White                                829      998    1027            1085
Anti-Black                               2731     3281    3475            2694
Anti-American Indian/Alaskan Native        83       97     100              97
Anti-Asian/Pacific Islander               217      252     266             188
Anti-Multiple Races, Group                182      235     251             109

In [35]:
religion = df[5:12]
religion

                               Incidents Offenses Victims Known Offenders
Bias motivation
Anti-Jewish                          954     1003    1076             330
Anti-Catholic                         57       57      68              37
Anti-Protestant                       38       43      48              28
Anti-Islamic                         156      193     201             124
Anti-Other Religion                  128      140     147              68
Anti-Multiple Religions, Group        35       37      39              14
Anti-Atheism/Agnosticism/etc.          6        7       7               3

In [36]:
sexual_orientation = df[12:17]
sexual_orientation

                       Incidents Offenses Victims Known Offenders
Bias motivation
Anti-Male Homosexual         738      855     902             832
Anti-Female Homosexual       164      201     212             163
Anti-Homosexual              245      297     314             224
Anti-Heterosexual             33       35      36              22
Anti-Bisexual                 17       18      18              17

In [38]:
ethnicity = df[17:19]
ethnicity

,Incidents,Offenses,Victims,Known Offenders
Bias motivation,,,,
Anti-Hispanic,475,611,646,585
Anti-Other Ethnicity/National Origin,497,590,608,462

In [41]:
disability = df[-3:-1]
disability

                Incidents Offenses Victims Known Offenders
Bias motivation
Anti-Physical          23       23      24              16
Anti-Mental            34       48      49              38