In [1]:
import pandas as pd

In [2]:
df = pd.read_stata('2002_ML.dta')

In [3]:
#dropping columns with NaN's 
df = df.dropna(axis = 1)

In [4]:
df['BIASMO1'].value_counts()#[df['STATNUM'] == 'Wyoming']

Anti-Black                  2487
Anti-Jewish                  931
Anti-Male Homosexual         825
Anti-White                   719
Anti-Other ethnicity         622
Anti-Hispanic                481
Anti-Homosexual (both)       223
Anti-Asian                   217
Anti-Other Religion          198
Anti-Female Homosexual       172
Anti-Multi-Racial            158
Anti-Islamic                 155
Anti-Am Indian                62
Anti-Protestant               55
Anti-Catholic                 53
Anti-Multi-Religious          31
Anti-Mental Disability        25
Anti-Physical Disability      20
Anti-Bisexual                 15
Anti-Heterosexual             10
Anti-Atheism/Agnosticism       3
Name: BIASMO1, dtype: int64

In [5]:
df2 = pd.read_stata('23600-0001-Data.dta')

In [6]:
df2['HC_FLAG'].value_counts()

No hate crime incidents present             18421
One or more hate crime incidents present     1967
Name: HC_FLAG, dtype: int64

In [7]:
df2.columns

Index(['REC_BH', 'STATNUM', 'ORI', 'BINCIDNO', 'ORIADDDT', 'ORINIBRS', 'CITY',
       'STATECOD', 'POPGRP', 'DIVISN', 'REGION', 'AGINDIC', 'CORECTY',
       'COVBYORI', 'FIELDNO', 'JUDDIST', 'NBRSFLG', 'INACTDTE', 'POP1',
       'COUNTY1', 'MSA1', 'LSTPOP1', 'POP2', 'COUNTY2', 'MSA2', 'LSTPOP2',
       'POP3', 'COUNTY3', 'MSA3', 'LSTPOP3', 'POP4', 'COUNTY4', 'MSA4',
       'LSTPOP4', 'POP5', 'COUNTY5', 'MSA5', 'LSTPOP5', 'MASTERYR', 'QTR1ACT',
       'QTR2ACT', 'QTR3ACT', 'QTR4ACT', 'F1QACT', 'F2QACT', 'F3QACT', 'F4QACT',
       'AGNAME', 'CFIPS1', 'CFIPS2', 'CFIPS3', 'CFIPS4', 'CFIPS5', 'HC_FLAG'],
      dtype='object')

In [8]:
df3 = pd.read_stata('2003_ML.dta')

In [9]:
df3

,REC_IR,STATNUM,ORI,ORIADDDT,ORINIBRS,CITY,STATECOD,POPGRP,DIVISN,REGION,...,VTYP_O9,VTYP_U9,VTYP_I10,VTYP_B10,VTYP_F10,VTYP_G10,VTYP_R10,VTYP_S10,VTYP_O10,VTYP_U10
0,IR,Alaska,AK0010100,19910430,NaN,ANCHORAGE,AK,1C,Pacific,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
1,IR,Alaska,AK0010100,19910430,NaN,ANCHORAGE,AK,1C,Pacific,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
2,IR,Alaska,AK0010100,19910430,NaN,ANCHORAGE,AK,1C,Pacific,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
3,IR,Alaska,AK0010100,19910430,NaN,ANCHORAGE,AK,1C,Pacific,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
4,IR,Alaska,AK0010100,19910430,NaN,ANCHORAGE,AK,1C,Pacific,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7484,IR,Wyoming,WY0110100,19910430,NaN,CHEYENNE,WY,3,Mountain,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
7485,IR,Wyoming,WY0110100,19910430,NaN,CHEYENNE,WY,3,Mountain,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
7486,IR,Wyoming,WY0110100,19910430,NaN,CHEYENNE,WY,3,Mountain,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
7487,IR,Wyoming,WY0130100,19910430,NaN,CASPER,WY,3,Mountain,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim
7488,IR,Wyoming,WY0150200,19910430,NaN,POWELL,WY,6,Mountain,West,...,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim,Not victim